### PR TITLE
Create a test case around Sidekiq 7.1

### PR DESCRIPTION
**Pull request by thenathanjones**
## Context

As per https://github.com/zormandi/logcraft-sidekiq/issues/1 we're keen to look at using this library against Sidekiq 7.

## What's changed?
- Add Sidekiq 7.1 to the test matrix.
- Loosen the gemspec version so it works with either 6 or 7.

### CODE REVIEW

**Comment by thenathanjones** [comment]
Apologies, I forgot to add the new files in my haste to get something up.

**Comment by zormandi** [comment]
Unfortunately, the interface seems to have changed (again). 😞 I'll try to take a look at it this weekend - unless you beat me to it.

**Comment by thenathanjones** [comment]
Of course they did 😅 

I'm probably not going to get to this until later next week myself (I was being opportunistic with the PR 😛).

**Comment by zormandi** [comment]
I released a new version that supports Sidekiq 7 so I'll close this PR. Thanks for bringing up the issue, though.

**Pull request closed without merging**
